import static java.nio.charset.StandardCharsets.UTF_8

plugins {
    id 'java'
    id 'signing'
    alias libs.plugins.publish
    alias libs.plugins.osdetector
}

group = 'io.github.honhimw'
version = libs.versions.version.get()
description = 'Generate UUIDs via Rust FFI integration.'

def title = 'UUID generator'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    options.encoding = UTF_8.name()
//    inputs.files(tasks.withType(ProcessResources))
//    options.compilerArgs << "-Werror" << "-Xlint:deprecation" << "-Xlint:unchecked"
}

dependencies {
    compileOnly libs.jspecify

    testImplementation platform(libs.junit)
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.platform:junit-platform-engine'
    testImplementation 'org.junit.platform:junit-platform-launcher'

    testImplementation libs.jmh.core
    testAnnotationProcessor libs.jmh.generator.annprocess
}

tasks.register('buildRust', Exec) {
    commandLine 'cargo', 'build', '--release', '--target', currentTarget()
    workingDir "${projectDir}"
    environment CARGO_TERM_COLOR: 'always'
}

tasks.register('cleanRust', Exec) {
    commandLine 'cargo', 'clean'
    workingDir "${projectDir}"
    environment CARGO_TERM_COLOR: 'always'
}

tasks.register('copyNativeLib', Copy) {
    dependsOn 'buildRust'
    def target = currentTarget()
    from("${projectDir}/../../target/${target}/release") {
        include "*.dll", "*.so", "*.dylib"

        eachFile { fileCopyDetails ->
            def ext = fileCopyDetails.name.substring(fileCopyDetails.name.lastIndexOf('.') + 1)
            def base = fileCopyDetails.name.substring(0, fileCopyDetails.name.lastIndexOf('.'))
            fileCopyDetails.name = "${base}-${target}.${ext}"
        }
    }
    into sourceSets.main.output.resourcesDir
    finalizedBy 'build'
}

tasks.register('cargoCheck', Exec) {
    commandLine 'cargo', 'check'
    workingDir "${projectDir}"
    environment CARGO_TERM_COLOR: 'always'
}

tasks.register('copyPreBuildLibs', Copy) {
    dependsOn 'cargoCheck'
    def dirs = [
            'linux',
            'windows',
            'macos',
            'macos-intel',
    ]
    dirs.each { dir ->
        from("${projectDir}/../../artifacts/${dir}") {
            include "*.dll", "*.so", "*.dylib"
        }
        into sourceSets.main.output.resourcesDir
    }
}

javadoc.dependsOn('copyNativeLib')
compileTestJava.dependsOn('copyNativeLib')

jar {
    enabled true
    if (System.getenv('USE_PREBUILT_LIBS') != null) {
        dependsOn 'copyPreBuildLibs'
    } else {
        dependsOn 'copyNativeLib'
//        archiveClassifier = osdetector.classifier
    }
}

tasks.register('linux_x86_64', Jar) {
    archiveClassifier = 'linux-x86_64'
    from(sourceSets.main.output) {
        exclude '*.dll', '*.dylib', '*aarch64*.so'
    }
}

tasks.register('linux_aarch64', Jar) {
    archiveClassifier = 'linux-aarch_64'
    from(sourceSets.main.output) {
        exclude '*.dll', '*.dylib', '*x86_64*.so'
    }
}

tasks.register('windows_x86_64', Jar) {
    archiveClassifier = 'windows-x86_64'
    from(sourceSets.main.output) {
        exclude '*.so', '*.dylib', '*aarch64*.dll'
    }
}

tasks.register('windows_aarch64', Jar) {
    archiveClassifier = 'windows-aarch_64'
    from(sourceSets.main.output) {
        exclude '*.so', '*.dylib', '*x86_64*.dll'
    }
}

tasks.register('macos_aarch64', Jar) {
    archiveClassifier = 'osx-aarch_64'
    from(sourceSets.main.output) {
        exclude '*.so', '*.dll', '*x86_64*.dylib'
    }
}

tasks.register('macos_x86_64', Jar) {
    archiveClassifier = 'osx-x86_64'
    from(sourceSets.main.output) {
        exclude '*.so', '*.dll', '*aarch64*.dylib'
    }
}


clean {
    dependsOn 'cleanRust'
}

test {
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(group as String, name, version as String)

    pom {
        name = title
        description = project.description
        url = 'https://github.com/honhimW/uuid'
        licenses {
            license {
                name = 'The Apache License, Version 2.0'
                url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                distribution = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
            }
        }
        developers {
            developer {
                id = 'honhimw'
                name = 'honhimw'
                url = 'https://honhimW.github.io'
                email = 'honhimw@outlook.com'
            }
        }
        scm {
            url = 'https://github.com/honhimW/uuid'
            connection = 'scm:git:git://github.com/honhimW/uuid.git'
            developerConnection = 'scm:git:ssh://github.com/honhimW/uuid.git'
        }
    }

}

String currentTarget() {
    if (osdetector.os == 'linux') {
        if (osdetector.arch == 'aarch_64') {
            return 'aarch64-unknown-linux-gnu'
        } else {
            return 'x86_64-unknown-linux-gnu'
        }
    } else if (osdetector.os == 'windows') {
        if (osdetector.arch == 'aarch64') {
            return 'aarch64-pc-windows-msvc'
        } else {
            return 'x86_64-pc-windows-msvc'
        }
    } else if (osdetector.os == 'macos') {
        if (osdetector.arch == 'aarch64') {
            return 'aarch64-apple-darwin'
        } else {
            return 'x86_64-apple-darwin'
        }
    }
    return ''
}
