# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:

jobs:
  cargo-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest, macos-13]
    steps:
      - uses: actions/Checkout@v5
      - name: Cargo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --manifest-path bindings/java/Cargo.toml
      - name: rust-toolchain
        if: matrix.os == 'ubuntu-22.04'
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
      - name: Cargo Cross
        if: matrix.os == 'ubuntu-22.04'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu --release --manifest-path bindings/java/Cargo.toml
      - name: Cargo Cross
        if: matrix.os == 'windows-latest'
        run: |
          rustup target add aarch64-pc-windows-msvc
          cargo build --target aarch64-pc-windows-msvc --release --manifest-path bindings/java/Cargo.toml
      - name: Rename Linux Files
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mkdir artifacts
          mv ./target/x86_64-unknown-linux-gnu/release/libuuid_java.so artifacts/uuid_java-x86_64-unknown-linux-gnu.so
          mv ./target/aarch64-unknown-linux-gnu/release/libuuid_java.so artifacts/uuid_java-aarch64-unknown-linux-gnu.so
      - name: Rename Windows Files
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          mv ./target/release/uuid_java.dll artifacts/uuid_java-x86_64-pc-windows-msvc.dll
          mv ./target/aarch64-pc-windows-msvc/release/uuid_java.dll artifacts/uuid_java-aarch64-pc-windows-msvc.dll
      - name: Rename Macos Files
        if: matrix.os == 'macos-latest'
        run: |
          mkdir artifacts
          mv ./target/release/libuuid_java.dylib artifacts/uuid_java-aarch64-apple-darwin.dylib
      - name: Rename Macos(Intel) Files
        if: matrix.os == 'macos-13'
        run: |
          mkdir artifacts
          mv ./target/release/libuuid_java.dylib artifacts/uuid_java-x86_64-apple-darwin.dylib

      - name: Upload Linux
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./artifacts/*
          compression-level: 9
          retention-days: 1
      - name: Upload Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./artifacts/*
          compression-level: 9
          retention-days: 1
      - name: Upload Macos AARCH64
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: ./artifacts/*
          compression-level: 9
          retention-days: 1
      - name: Upload Macos AMD64
        if: matrix.os == 'macos-13'
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel
          path: ./artifacts/*
          compression-level: 9
          retention-days: 1
  
  gradle-build:
    needs: cargo-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/Checkout@v5
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

       # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
       # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Gradle build
        run: |
          bash bindings/java/gradlew --project-dir bindings/java build -x test
          bash bindings/java/gradlew --project-dir bindings/java linux_x86_64
          bash bindings/java/gradlew --project-dir bindings/java linux_aarch64
          bash bindings/java/gradlew --project-dir bindings/java windows_x86_64
          bash bindings/java/gradlew --project-dir bindings/java windows_aarch64
          bash bindings/java/gradlew --project-dir bindings/java macos_aarch64
          bash bindings/java/gradlew --project-dir bindings/java macos_x86_64
          bash bindings/java/gradlew --project-dir bindings/java plainJavadocJar
          bash bindings/java/gradlew --project-dir bindings/java generatePomFileForMavenPublication
        env:
          USE_PREBUILT_LIBS: true
#      - name: Upload bundles
#        uses: actions/upload-artifact@v4
#        with:
#          name: jars
#          path: ./bindings/java/build/libs/*
#          compression-level: 9
#          retention-days: 1
      - name: Signing
        run: |
          echo $SECRING_GPG_BASE64 | base64 --decode > secring.gpg
          gpg --import --passphrase $SIGNING_KEY_PASSWORD --pinentry-mode loopback ./secring.gpg
          mkdir workspace
          mv ./bindings/java/build/libs/* ./workspace
          mv ./bindings/java/build/publications/maven/pom-default.xml ./workspace/pom.xml
          cd workspace
          mv pom.xml "$(find . -maxdepth 1 -type f -regex './uuid-[0-9]+\.[0-9]+\.[0-9]+\.jar' | sed 's/\.jar$/.pom/' | head -n1)"
          for i in *.jar *.pom; do gpg --yes --armor --detach-sign --passphrase $SIGNING_KEY_PASSWORD --pinentry-mode loopback --local-user $SIGNING_KEY_ID; done
          for i in *.jar *.pom; do md5sum "$i" | awk '{print $1}' > "$i.md5"; done
          for i in *.jar *.pom; do sha1sum "$i" | awk '{print $1}' > "$i.sha1"; done
          for i in *.jar *.pom; do sha256sum "$i" | awk '{print $1}' > "$i.sha256"; done
          for i in *.jar *.pom; do sha512sum "$i" | awk '{print $1}' > "$i.sha512"; done
          ls -lah
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SECRING_GPG_BASE64: ${{ secrets.SECRING_GPG }}
      - name: Publishing
        run: |
          export ARTIFACT_NAME="$(find . -maxdepth 1 -type f -regex './uuid-[0-9]+\.[0-9]+\.[0-9]+\.jar' | head -n1 | sed -E 's|.*/||; s|\.jar$||')"
          cd workspace
          zip -r artifacts.zip ./*
          curl -X POST "https://central.sonatype.com/api/v1/publisher/upload?name=${ARTIFACT_NAME}&publishingType=USER_MANAGED" \
            -u "$MAVEN_CENTRAL_USERNAME:$MAVEN_CENTRAL_PASSWORD" \
            -H 'Content-Type: multipart/form-data' \
            -F "file=@artifacts.zip"
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
#      - name: Publishing
#        run: |
#          bash bindings/java/gradlew --project-dir bindings/java publishAllPublicationsToMavenCentralRepository
#        env:
#          USE_PREBUILT_LIBS: true
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
