# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest, macos-13]
    steps:
      - uses: actions/Checkout@v5
      - name: Cargo
        uses: actions-rs/cargo@v1
        with:
            use-cross: true
            command: build
            args: --release
      - name: rust-toolchain
        if: matrix.os == 'ubuntu-22.04'
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
      - name: Cargo Cross
        if: matrix.os == 'ubuntu-22.04'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu --release
      - name: Cargo Cross
        if: matrix.os == 'windows-latest'
        run: |
          rustup target add aarch64-pc-windows-msvc
          cargo build --target aarch64-pc-windows-msvc --release
      - name: Upload Linux AMD64
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: uuid_java-x86_64-unknown-linux-gnu
          path: ./target/release/uuid_java.so
          compression-level: 9
          retention-days: 1
      
      - name: Upload Linux AARCH64
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: uuid_java-aarch64-unknown-linux-gnu
          path: ./target/aarch64-unknown-linux-gnu/release/uuid_java.so
          compression-level: 9
          retention-days: 1

      - name: Upload Windows AMD64
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: uuid_java-x86_64-pc-windows-msvc
          path: ./target/release/uuid_java.dll
          compression-level: 9
          retention-days: 1
      
      - name: Upload Windows AARCH64
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: uuid_java-aarch64-pc-windows-msvc
          path: ./target/aarch64-pc-windows-msvc/release/uuid_java.dll
          compression-level: 9
          retention-days: 1

      - name: Upload Macos AARCH64
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: uuid_java-aarch64-apple-darwin
          path: ./target/release/uuid_java.dylib
          compression-level: 9
          retention-days: 1
      
      - name: Upload Macos AMD64
        if: matrix.os == 'macos-13'
        uses: actions/upload-artifact@v4
        with:
          name: uuid_java-x86_64-apple-darwin
          path: ./target/release/uuid_java.dylib
          compression-level: 9
          retention-days: 1
  

  collect:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: List downloaded files
        run: ls -R ./artifacts

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'

      # # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
  
      # - name: Build with Gradle Wrapper
      #   run: bash bindings/java/gradlew --project-dir bindings/java clean build
